version: "3.9"
services:
  app:
    build: .
    container_name: trader_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    command: uvicorn trader.app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app/src
  postgres:
    image: postgres:16-alpine
    container_name: trader_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-trader}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: trader_redis
    ports:
      - "6379:6379"
volumes:
  pgdata: